# Generated by Django 5.2.6 on 2026-01-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
