# Generated by Django 6.0 on 2026-02-19 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_user_is_email_verified_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=100)),
                ('property_type', models.CharField(choices=[('TELEMETRY', 'Telemetry (Read-Only)'), ('COMMAND', 'Command (Write or Read/Write)')], max_length=20)),
                ('data_type', models.CharField(choices=[('BINARY', 'Binary (On/Off)'), ('RANGE', 'Number Range'), ('TEXT', 'Text / Enum')], max_length=20)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='devices.device')),
            ],
            options={
                'unique_together': {('device', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='CommandQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_value', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Delivery'), ('DELIVERED', 'Delivered to Device'), ('EXECUTED', 'Executed & Confirmed'), ('FAILED', 'Failed / Timeout')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
                ('target_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceproperty')),
            ],
        ),
        migrations.DeleteModel(
            name='DeviceCommand',
        ),
    ]
