# Generated by Django 5.2.6 on 2026-03-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_deviceproperty_commandqueue_delete_devicecommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Delivery'), ('DELIVERED', 'Delivered to Device'), ('EXECUTED', 'Executed & Confirmed'), ('FAILED', 'Failed / Timeout'), ('CANCELLED', 'Cancelled by User')], default='PENDING', max_length=20),
        ),
    ]
