# Generated by Django 5.2.6 on 2026-03-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_commandqueue_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandqueue',
            old_name='executed_at',
            new_name='expires_at',
        ),
        migrations.AddField(
            model_name='commandqueue',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commandqueue',
            name='max_retries',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='commandqueue',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commandqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commandqueue',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commandqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued in Redis'), ('DELIVERED', 'Delivered to Device'), ('EXECUTED', 'Acknowledged Execution'), ('FAILED', 'Execution Failed'), ('CANCELLED', 'Cancelled by User'), ('EXPIRED', 'TTL Expired')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='commandqueue',
            index=models.Index(fields=['device', 'status'], name='devices_com_device__2ff894_idx'),
        ),
        migrations.AddIndex(
            model_name='commandqueue',
            index=models.Index(fields=['status', 'expires_at'], name='devices_com_status_6bb0d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='commandqueue',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('device', 'idempotency_key'), name='unique_command_idempotency'),
        ),
        migrations.AlterModelTable(
            name='commandqueue',
            table='devices_commandqueue',
        ),
    ]
