"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

import dj_database_url
import certifi
from pathlib import Path
from celery.schedules import crontab



# Fix Windows TLS certificate path
os.environ['SSL_CERT_FILE'] = certifi.where()
os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "sk-apikey"

# This sets DEBUG to False if you are on Render, and True otherwise.
DEBUG = not os.environ.get('RENDER')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_HOST_USER = 'resend'
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "postmaster@sandboxf8eb86c158ba407aa6cf65c14dee2cb9.mailgun.org")
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EMAIL_TIMEOUT = 30


ALLOWED_HOSTS = [
    'iot-bridge.onrender.com', 
    '127.0.0.1', 
    'localhost',
    '.onrender.com',
    ]

# telling the app to use my user model
AUTH_USER_MODEL = 'devices.User'


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'devices',
    'telemetry',
    'django_extensions',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'anymail',
]

# If we are on Render, use Redis. If Local, use Memory.
if os.environ.get('RENDER'):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [os.environ.get('REDIS_URL')],
                # "hosts": [("redis-channels-url.render.com", 6379)],
                "capacity": 1500,  # Drop messages if the client queue exceeds 1500
                "expiry": 10,    # Expire unread messages after 10 seconds
        
            },
        },
    }
else:
    # 🚨 FOR LOCAL DEVELOPMENT (No Redis required)
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# cors configuration
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://iotb-frontend.vercel.app",
    os.environ.get('FRONTEND_URL', 'https://iotb-frontend.vercel.app'),
]

CSRF_TRUSTED_ORIGINS = [
    "https://iot-bridge.onrender.com",
    "https://iotb-frontend.vercel.app"
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# definition of how the API system handles authentication.
REST_FRAMEWORK = {

    # definition of how the API system handles authentication.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],

    # throttling global configuration
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '500/day',      # Unauthenticated users (Register/Login)
        'user': '10000/day',    # Authenticated users (Dashboard usage)
        'burst': '60/minute',  # For sensitive endpoints
        'ingestion': '6000/minute',  # 🚀 NEW INDUSTRIAL LANE: 6000 requests per minute (100 req/sec)
    }
}
ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'core.asgi.application'

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get(
            'DATABASE_URL',
            'postgresql://iot_user:wale%400811@127.0.0.1:5432/iot_bridge_db'
        ),
        conn_max_age=600,
        conn_health_checks=True,
    )
} 

# Redis cache
if os.environ.get('RENDER'):
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": os.environ.get('REDIS_URL'),
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
    CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL')

else:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": "redis://127.0.0.1:6379/1",
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            }
        }
    }
    CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"

CELERY_BROKER_URL = os.environ.get('REDIS_URL', "redis://127.0.0.1:6379/0")

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

CELERY_BEAT_SCHEDULE = {
    'rollup-raw-to-1m': {
        'task': 'telemetry.tasks.task_rollup_raw_to_1m',
        'schedule': crontab(minute='*'), # Runs every minute
    },
    'rollup-1m-to-5m': {
        'task': 'telemetry.tasks.task_rollup_1m_to_5m',
        'schedule': crontab(minute='*/5'), # Runs every 5 minutes
    },
    'rollup-5m-to-1h': {
        'task': 'telemetry.tasks.task_rollup_5m_to_1h',
        'schedule': crontab(minute='0'), # Runs at the top of every hour
    },
    'rollup-1h-to-1d': {
        'task': 'telemetry.tasks.task_rollup_1h_to_1d',
        'schedule': crontab(hour='0', minute='5'), # Runs daily at 00:05
    },
}

# MQTT Broker Configuration
MQTT_BROKER_URL = os.environ.get('MQTT_BROKER_URL', 'localhost')
MQTT_BROKER_PORT = int(os.environ.get('MQTT_BROKER_PORT', 1883))

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# handling media
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# telling the engine to use 64-bit for id in other to accomodate for large number of rows
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


