# Generated by Django 5.2.6 on 2026-04-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telemetry_telemetrylog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlertThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('operator', models.CharField(choices=[('>', 'Greater Than'), ('<', 'Less Than'), ('=', 'Equals')], default='>', max_length=1)),
                ('notification_channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=10)),
                ('notification_target', models.CharField(blank=True, help_text='Email address or phone number, depending on notification channel.', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('cooldown_minutes', models.IntegerField(default=60)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorResult1Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('bucket', models.DateTimeField()),
                ('indicators', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'telemetry_indicator_1d',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_i_device__8199eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='uniq_ind_1d')],
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult1Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('bucket', models.DateTimeField()),
                ('indicators', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'telemetry_indicator_1h',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_i_device__260330_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='uniq_ind_1h')],
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult1Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('bucket', models.DateTimeField()),
                ('indicators', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'telemetry_indicator_1m',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_i_device__228809_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='uniq_ind_1m')],
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('bucket', models.DateTimeField()),
                ('indicators', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'telemetry_indicator_5m',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_i_device__8c777e_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='uniq_ind_5m')],
            },
        ),
        migrations.CreateModel(
            name='MediaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to='iot_media/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_logs', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryRollup1Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('label', models.CharField(max_length=50)),
                ('bucket', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceproperty')),
            ],
            options={
                'db_table': 'telemetry_rollup_1d',
                'indexes': [models.Index(fields=['device_id', 'property', '-bucket'], name='telemetry_r_device__9d5e95_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property', 'bucket'), name='unique_1d_bucket')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRollup1Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('label', models.CharField(max_length=50)),
                ('bucket', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceproperty')),
            ],
            options={
                'db_table': 'telemetry_rollup_1h',
                'indexes': [models.Index(fields=['device_id', 'property', '-bucket'], name='telemetry_r_device__ea334c_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property', 'bucket'), name='unique_1h_bucket')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRollup1Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('label', models.CharField(max_length=50)),
                ('bucket', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceproperty')),
            ],
            options={
                'db_table': 'telemetry_rollup_1m',
                'indexes': [models.Index(fields=['device_id', 'property', '-bucket'], name='telemetry_r_device__cd961d_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property', 'bucket'), name='unique_1m_bucket')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRollup5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('label', models.CharField(max_length=50)),
                ('bucket', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.deviceproperty')),
            ],
            options={
                'db_table': 'telemetry_rollup_5m',
                'indexes': [models.Index(fields=['device_id', 'property', '-bucket'], name='telemetry_r_device__dc0e73_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property', 'bucket'), name='unique_5m_bucket')],
            },
        ),
    ]
