# Generated by Django 5.2.6 on 2026-04-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetrylog',
            options={},
        ),
    ]
