# Generated by Django 5.2.6 on 2026-01-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telemetrylog',
            index=models.Index(fields=['label'], name='telemetry_t_label_e0070b_idx'),
        ),
    ]
