# Generated by Django 6.0 on 2026-01-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_telemetrylog_telemetry_t_label_e0070b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertthreshold',
            name='cooldown_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='alertthreshold',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alertthreshold',
            name='operator',
            field=models.CharField(choices=[('>', 'Greater Than'), ('<', 'Less Than'), ('=', 'Equals')], default='>', max_length=1),
        ),
    ]
