# Generated by Django 5.2.6 on 2026-04-08 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('telemetry', '0002_alter_telemetrylog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrylog',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetrylog',
            name='property',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, to='devices.deviceproperty'),
            preserve_default=False,
        ),
    ]
