# Generated by Django 5.2.6 on 2026-03-18 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_partitioned_telemetry'),
        ('telemetry', '0003_alertthreshold_cooldown_minutes_and_more'),
    ]

    operations = [
    ]
