# Generated by Django 5.2.6 on 2026-04-02 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_telemetrylog_device_telemetrylog_property_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetrylog',
            options={'managed': True},
        ),
    ]
