# Generated by Django 5.2.6 on 2026-03-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_merge_20260318_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetrylog',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='IndicatorResult1Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('bucket', models.DateTimeField()),
                ('indicators', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'telemetry_indicator_1d',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_i_device__8199eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='uniq_ind_1d')],
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult1Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('bucket', models.DateTimeField()),
                ('indicators', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'telemetry_indicator_1h',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_i_device__260330_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='uniq_ind_1h')],
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult1Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('bucket', models.DateTimeField()),
                ('indicators', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'telemetry_indicator_1m',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_i_device__228809_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='uniq_ind_1m')],
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('bucket', models.DateTimeField()),
                ('indicators', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'telemetry_indicator_5m',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_i_device__8c777e_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='uniq_ind_5m')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRollup1Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('label', models.CharField(max_length=50)),
                ('bucket', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'telemetry_rollup_1d',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_r_device__9d5e95_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='unique_1d_bucket')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRollup1Hour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('label', models.CharField(max_length=50)),
                ('bucket', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'telemetry_rollup_1h',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_r_device__ea334c_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='unique_1h_bucket')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRollup1Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('label', models.CharField(max_length=50)),
                ('bucket', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'telemetry_rollup_1m',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_r_device__cd961d_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='unique_1m_bucket')],
            },
        ),
        migrations.CreateModel(
            name='TelemetryRollup5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField()),
                ('property_id', models.BigIntegerField()),
                ('label', models.CharField(max_length=50)),
                ('bucket', models.DateTimeField()),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
            ],
            options={
                'db_table': 'telemetry_rollup_5m',
                'indexes': [models.Index(fields=['device_id', 'property_id', '-bucket'], name='telemetry_r_device__dc0e73_idx')],
                'constraints': [models.UniqueConstraint(fields=('device_id', 'property_id', 'bucket'), name='unique_5m_bucket')],
            },
        ),
    ]
