# Generated by Django 5.2.6 on 2026-03-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_alertthreshold_notification_channel_and_target'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telemetrylog',
            table='telemetry_telemetrylog',
        ),
    ]
