# Generated by Django 5.2.6 on 2026-03-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_rename_executed_at_commandqueue_expires_at_and_more'),
        ('telemetry', '0007_alter_telemetrylog_table'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='telemetryrollup1day',
            name='unique_1d_bucket',
        ),
        migrations.RemoveConstraint(
            model_name='telemetryrollup1hour',
            name='unique_1h_bucket',
        ),
        migrations.RemoveConstraint(
            model_name='telemetryrollup1min',
            name='unique_1m_bucket',
        ),
        migrations.RemoveConstraint(
            model_name='telemetryrollup5min',
            name='unique_5m_bucket',
        ),
        migrations.RemoveIndex(
            model_name='telemetryrollup1day',
            name='telemetry_r_device__9d5e95_idx',
        ),
        migrations.RemoveIndex(
            model_name='telemetryrollup1hour',
            name='telemetry_r_device__ea334c_idx',
        ),
        migrations.RemoveIndex(
            model_name='telemetryrollup1min',
            name='telemetry_r_device__cd961d_idx',
        ),
        migrations.RemoveIndex(
            model_name='telemetryrollup5min',
            name='telemetry_r_device__dc0e73_idx',
        ),
        migrations.RemoveField(
            model_name='telemetryrollup1day',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='telemetryrollup1hour',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='telemetryrollup1min',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='telemetryrollup5min',
            name='property_id',
        ),
        migrations.AddField(
            model_name='telemetryrollup1day',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.deviceproperty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetryrollup1hour',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.deviceproperty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetryrollup1min',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.deviceproperty'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telemetryrollup5min',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='devices.deviceproperty'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='telemetryrollup1day',
            index=models.Index(fields=['device_id', 'property', '-bucket'], name='telemetry_r_device__9d5e95_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryrollup1hour',
            index=models.Index(fields=['device_id', 'property', '-bucket'], name='telemetry_r_device__ea334c_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryrollup1min',
            index=models.Index(fields=['device_id', 'property', '-bucket'], name='telemetry_r_device__cd961d_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryrollup5min',
            index=models.Index(fields=['device_id', 'property', '-bucket'], name='telemetry_r_device__dc0e73_idx'),
        ),
        migrations.AddConstraint(
            model_name='telemetryrollup1day',
            constraint=models.UniqueConstraint(fields=('device_id', 'property', 'bucket'), name='unique_1d_bucket'),
        ),
        migrations.AddConstraint(
            model_name='telemetryrollup1hour',
            constraint=models.UniqueConstraint(fields=('device_id', 'property', 'bucket'), name='unique_1h_bucket'),
        ),
        migrations.AddConstraint(
            model_name='telemetryrollup1min',
            constraint=models.UniqueConstraint(fields=('device_id', 'property', 'bucket'), name='unique_1m_bucket'),
        ),
        migrations.AddConstraint(
            model_name='telemetryrollup5min',
            constraint=models.UniqueConstraint(fields=('device_id', 'property', 'bucket'), name='unique_5m_bucket'),
        ),
    ]
